<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>El.Core</RootNamespace>
    <AssemblyName>El.Core</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Version>1.8.0</Version>
    <AssemblyVersion>1.8.0.0</AssemblyVersion>
    <FileVersion>1.8.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net45" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

</Project>
